### PR TITLE
fix: allow passByReference as a parameter and gh pages release

### LINKED ISSUE #9: preserve the type of the referenced value (if no head/tail)
from the OpenRPC spec:
https://github.com/open-rpc/spec/blob/master/spec.md#runtime-expression

image

### PR DESCRIPTION
**Pull request by shanejonas**
fixes #9

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -27,17 +39,25 @@ interface IParserObject {
...
+ * @param templateString a string that may contain template delimeters `${}` that refer to the JSON.
+ * @param passByReference allows you to return JSON objects by reference if there is no `head` or `tail`.
+ * @return a string OR a JSON value reference if `passByReference` is `true` and there is no `head` or `tail`.
  */
-function parse(jsonObject: any, templateString: string): string {
+function compileTemplate(
+  jsonObject: any,
+  templateString: string,
+  passByReference?: boolean,
+): string | any {
```
Comment (BelfordZ) [inline src/index.ts]: `string | any` isn't really any better than just `any`

**Comment by BelfordZ** [comment]
if the api has changed, shouldn't the readme be updated as well?
